# Site settings
title: Big ball of mud
email: riccardo.cardin@gmail.com
description: >
  Writing about Scala, Kotlin, and the JVM â€” from functional programming
  and effect systems to design patterns and concurrency.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rcardin.github.io" # the base hostname & protocol for your site
twitter_username: riccardo_cardin
github_username:  rcardin
linkedin_username:  riccardocardin
so_usename: riccardo-cardin
reddit_username: rcardin

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
